---
    inventory:
       plugin: NetBoxInventory2
       options:
         nb_url: "<add netbox URL here>"
         nb_token: "<add netbox token here>"
         ssl_verify: False
         use_platform_slug: True

    runner: 
        plugin: threaded
        options:
            num_workers: 50
